### ISSUE TITLE
Also export answers of other users on questions/answers you participated in

### ISSUE THREAD

**Issue by rubo77** [ryancwalsh/StackExchangeBackupLaravelPHP#1]
I would like to have an export of all questions and answers where I took part of. so the easiest way would be to create a list of all stack exchange sites where I was active on and download that whole pages

**Comment by ryancwalsh** [comment]
@rubo77 If you are asking whether it first figures out which questions you participated in and then downloads each of those questions plus ALL of the answers (including ones from people other than you), no it does not.

But I'm happy to accept a pull request if you figure out how to add that as a configurable feature.

**Comment by rubo77** [comment]
solved in #10
