### ISSUE TITLE
composer not working

### ISSUE THREAD

**Issue by rubo77** [ryancwalsh/StackExchangeBackupLaravelPHP#2]
I tried the following:

On my  Debian jessie server as root I installed composer globally with

    curl -sS https://getcomposer.org/installer | sudo php -- --install-dir=/usr/local/bin --filename=composer

then as user I cloned your repository and in the main folder of the repo I called :

```
$ composer require ryancwalsh/stack-exchange-backup-laravel
                                 
  [InvalidArgumentException]                                                                                                                                                             
  Could not find a version of package ryancwalsh/stack-exchange-backup-laravel matching your minimum-stability (stable). Require it with an explicit version constraint allowing its de  
  sired stability.                                                                             

```

**Comment by ryancwalsh** [comment]
I found https://stackoverflow.com/a/41149676/470749, which led me to try this, which worked:

`composer require ryancwalsh/stack-exchange-backup-laravel:dev-master`

I'll update the docs.

Thanks.

**Comment by rubo77** [comment]
Why not merging dev-master into master?

**Comment by ryancwalsh** [comment]
@rubo77 "dev-master" is not the name of a branch. It's a special reserved word as described at these links:

* https://stackoverflow.com/q/19009334/470749
* https://getcomposer.org/doc/articles/aliases.md

I just haven't learned very much about versioning and how to publish open source code for others to use. I'm still trying to figure it out.
