### ISSUE TITLE
minimum PHP version missing in Readme

### ISSUE THREAD

**Issue by rubo77** [ryancwalsh/StackExchangeBackupLaravelPHP#3]
I get the error

>   [InvalidArgumentException]                                                                                                                
>   Package ryancwalsh/stack-exchange-backup-laravel at version dev-master has a PHP requirement incompatible with your PHP version (5.6.40)  
>                                                                                                                                             

and on another server:

> [InvalidArgumentException]                                                                                                                
>   Package ryancwalsh/stack-exchange-backup-laravel at version dev-master has a PHP requirement incompatible with your PHP version (7.0.33) 

I upgraded to PHP 7.3, which works fine.

**Comment by ryancwalsh** [comment]
Agreed; I'll add it. Thanks.
