### ISSUE TITLE
install problems

### ISSUE THREAD

**Issue by rubo77** [ryancwalsh/StackExchangeBackupLaravelPHP#4]
Ǹow I got this on php7.3:

```
$ composer require ryancwalsh/stack-exchange-backup-laravel:dev-master

composer require ryancwalsh/stack-exchange-backup-laravel:dev-master
./composer.json has been updated
Root package 'ryancwalsh/stack-exchange-backup-laravel' cannot require itself in its composer.json
Did you accidentally name your root package after an external package?
```

**Comment by ryancwalsh** [comment]
@rubo77 I don't think I understand. In your example above, it looks like you accidentally called `composer require ryancwalsh/stack-exchange-backup-laravel:dev-master` twice, which would cause a problem.

**Comment by rubo77** [comment]
Where should I have called it twice?

I cloned the repository then I went into the directory and called composer once

**Comment by rubo77** [comment]
Maybe you try it yourself and install it on a clean machine then you copy and paste the history of your command line here so I can copy and paste it to successfully installed on my machine

**Comment by ryancwalsh** [comment]
@rubo77 Thanks for your patience. I found that some parts of the code were broken, and I've now fixed those problems and updated the Readme and tested the installation and the exporting of StackExchange json, and it seems to work for me. Does it work for you now?

**Comment by rubo77** [comment]
seems not to work, This is what I tried: (maybe add this to the readme):

```
composer global require laravel/installer
# on Ubuntu:
echo 'export PATH="$PATH:$HOME/.config/composer/vendor/bin"' >> ~/.bashrc
# on Debian:
echo 'export PATH="$PATH:$HOME/.composer/vendor/bin"' >> ~/.bashrc
# apply
source ~/.bashrc
# install test
laravel new testblog
# if the creation runs fine, test it or just
rm -Rf testblog
chmod o+w composer.json 
su rubo77
composer require ryancwalsh/stack-exchange-backup-laravel:dev-master --prefer-source

```

This is the error:

```
./composer.json has been updated
Root package 'ryancwalsh/stack-exchange-backup-laravel' cannot require itself in its composer.json
Did you accidentally name your root package after an external package?
```

**Comment by rubo77** [comment]
I see the error: you cannot call `composer require ryancwalsh/stack-exchange-backup-laravel:dev-master --prefer-source` inside the git repository folder. instead create a new folder, where you want your app running. I will add instructions to the readme....

**Comment by ryancwalsh** [comment]
I see that you already figured out ([here](https://github.com/ryancwalsh/StackExchangeBackupLaravelPHP/issues/9) and [here](https://github.com/ryancwalsh/StackExchangeBackupLaravelPHP/issues/8)) that you can just omit AWS credentials and then ignore the errors.

I appreciate your suggestions for the improved readme file to help people who aren't familiar with Laravel. 

The formatting got messed up from how I had it, so I guess I'll try to make similar changes instead of merging the pull request.

**Comment by rubo77** [comment]
lets discuss that in #6
