### ISSUE TITLE
remove AWS dependency

### ISSUE THREAD

**Issue by rubo77** [ryancwalsh/StackExchangeBackupLaravelPHP#8]
I think addind AWS as a dependency is not needed.

for example, I would like to store the files locally on my mashine in a subfolder that I can make accessible via nginx myself.

**Comment by ryancwalsh** [comment]
Next time I work on that part of the code, I'll probably add an option to control whether it attempts to save to AWS. Then there will not be errors in the console if you omit the credentials from `.env`.

**Comment by ryancwalsh** [comment]
@rubo77 I made a bunch of changes today, and now there is an option to skip uploading to S3. Note that this project now uses Laravel 6.0.
