### ISSUE TITLE
 ErrorException  : Undefined index: access_token

### ISSUE THREAD

**Issue by rubo77** [ryancwalsh/StackExchangeBackupLaravelPHP#9]
after downloading a lot already, suddenly this error:

```
json
Saved to StackExchange/2019-07-14_084258_UTC/Ask_Ubuntu/answers/page_0002.json
ERROR: There was a problem trying to write to AWS S3. Check the logs. StackExchange/2019-07-14_084258_UTC/Ask_Ubuntu/answers/page_0002.json
Saved to StackExchange/2019-07-14_084258_UTC/Ask_Ubuntu/answers/page_0003.json
ERROR: There was a problem trying to write to AWS S3. Check the logs. StackExchange/2019-07-14_084258_UTC/Ask_Ubuntu/answers/page_0003.json
Saved to StackExchange/2019-07-14_084258_UTC/Ask_Ubuntu/questions/page_0001.json
ERROR: There was a problem trying to write to AWS S3. Check the logs. StackExchange/2019-07-14_084258_UTC/Ask_Ubuntu/questions/page_0001.json

   ErrorException  : Undefined index: access_token

  at /tmp/st/webapp/vendor/ryancwalsh/stack-exchange-backup-laravel/src/ExportStackExchangeHelper.php:89
    85|                     //Log::debug('$accessTokenResponseJsonString = ' . $accessTokenResponseJsonString);
    86|                     return $accessTokenResponseJsonString;
    87|                 });
    88|         $accessTokenArray = json_decode($accessTokenResponseJsonString, true);
  > 89|         return $accessTokenArray['access_token'];
    90|     }
    91| 
    92|     /**
    93|      * 

  Exception trace:

  1   Illuminate\Foundation\Bootstrap\HandleExceptions::handleError("Undefined index: access_token", "/tmp/st/webapp/vendor/ryancwalsh/stack-exchange-backup-laravel/src/ExportStackExchangeHelper.php", ["{"error_message":"Authorization code has already been used"}"])
      /tmp/st/webapp/vendor/ryancwalsh/stack-exchange-backup-laravel/src/ExportStackExchangeHelper.php:89

  2   ryancwalsh\StackExchangeBackupLaravel\ExportStackExchangeHelper::getAccessToken()
      /tmp/st/webapp/vendor/ryancwalsh/stack-exchange-backup-laravel/src/ExportStackExchangeHelper.php:102

  Please use the argument -v to see more details.

```

**Comment by ryancwalsh** [comment]
I see your error says "Authorization code has already been used", which is really bizarre if it happened right in the middle of everything. 

Maybe try the `php artisan exportStackExchange --flushCache` option to try again with a fresh code? 

I wonder if it somehow expired while you were using it. That hasn't happened to me.

**Comment by rubo77** [comment]
I tried again with

    time php artisan exportStackExchange --flushCache

after 1m 15s I get the same error at exactly the same page after

     Saved to StackExchange/2019-07-14_141522_UTC/Ask_Ubuntu/questions/page_0001.json

**Comment by ryancwalsh** [comment]
Your Laravel cache must not be working. It's supposed to cache the access_token for 60 minutes.

So I'd make sure your Laravel installation is set up correctly so that caching works: https://laravel.com/docs/5.6/cache#configuration

You could also uncomment the `Log::debug` lines here and get more hints about what's happening:
https://github.com/ryancwalsh/StackExchangeBackupLaravelPHP/blob/2444726deede8c689f1fa8b71f0feffc0c43a335/src/ExportStackExchangeHelper.php#L85

**Comment by rubo77** [comment]
seems like it is set to 60s plus the 15s i needed to copy the Token from the URL.

I couldn't find any setting in the cache config that sets this, is it set in there? or is it in some added module from composer?

**Comment by ryancwalsh** [comment]
Darn, it looks like newer versions of Laravel use seconds instead of minutes (https://laravel-news.com/cache-ttl-change-coming-to-laravel-5-8), and I bet your Laravel is newer than mine. 

I guess I'll update the code to work with newer Laravel versions and then document that requirement in the readme.

Also, the `Log::debug` line doesn't print anything to the console; you'll need to look at `storage/logs/laravel.log`.

**Comment by ryancwalsh** [comment]
In the meantime, go ahead and change the ExportStackExchangeHelper SESSION_MINS value to something much larger (in your local copy of the code). 

Your changes will then get clobbered when I update the repo (if you then pull the latest), but at least it will be a temporary fix.

**Comment by rubo77** [comment]
```
$ grep ' = ' storage/logs/laravel-2019-07-14.log
[2019-07-14 19:50:19] local.DEBUG: $accessTokenResponseJsonString = {"access_token":"q99uCfwBhJ7Y0w4ArMR*Hg))","expires":86400}  
[2019-07-14 19:51:20] local.DEBUG: $accessTokenResponseJsonString = {"error_message":"Authorization code has already been used"}  
[2019-07-14 19:56:36] local.DEBUG: $accessTokenResponseJsonString = {"access_token":"IqQMs13(iY(dXr1AQzjojQ))","expires":86400}  
[2019-07-14 19:57:36] local.DEBUG: $accessTokenResponseJsonString = {"error_message":"Authorization code has already been used"}  
```

**Comment by rubo77** [comment]
Why put a timeout there at all? the download can take some days if you have a slow connection or loads of activity, so lets set this to 999999999999

**Comment by ryancwalsh** [comment]
@rubo77 I made a bunch of changes today and believe this is fixed. Note that this project now uses Laravel 6.0.
